"""testing 1

Revision ID: 2cf5ef2e61ea
Revises: e99a49559851
Create Date: 2024-11-06 15:12:02.857078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cf5ef2e61ea'
down_revision: Union[str, None] = 'e99a49559851'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('product', sa.String(), nullable=True))
    op.create_index(op.f('ix_profiles_product'), 'profiles', ['product'], unique=False)
    op.drop_index('ix_users_username', table_name='users')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.drop_index(op.f('ix_profiles_product'), table_name='profiles')
    op.drop_column('profiles', 'product')
    # ### end Alembic commands ###
