"""Initial migration: create users and profiles tables_2

Revision ID: 629b9a0d9c5a
Revises: bb963ddac720
Create Date: 2024-11-05 22:11:41.311596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '629b9a0d9c5a'
down_revision: Union[str, None] = 'bb963ddac720'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'profiles', ['profile_id'], ['profile_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'profile_id')
    # ### end Alembic commands ###
