"""Initial migration: testing suresh

Revision ID: 8032ba6c25d8
Revises: c3c8640e0967
Create Date: 2024-11-06 12:30:23.976042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8032ba6c25d8'
down_revision: Union[str, None] = 'c3c8640e0967'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('address', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_address'), 'users', ['address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_address'), table_name='users')
    op.drop_column('users', 'address')
    # ### end Alembic commands ###
