"""Initial migration: create users and profiles tables_1

Revision ID: bb963ddac720
Revises: d22d38b518a0
Create Date: 2024-11-05 22:11:07.390061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb963ddac720'
down_revision: Union[str, None] = 'd22d38b518a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_index(op.f('ix_profiles_bio'), 'profiles', ['bio'], unique=False)
    op.create_index(op.f('ix_profiles_profile_id'), 'profiles', ['profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profiles_profile_id'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_bio'), table_name='profiles')
    op.drop_table('profiles')
    # ### end Alembic commands ###
